channels:
- conda-forge
dependencies:
- python=3.11.5
- pip<=23.3.1
- pip:
  - mlflow==2.10.2
  - cloudpickle==2.2.1
  - ipython==8.20.0
  - keras-tuner==1.4.7
  - namex==0.0.7
  - numpy==1.23.5
  - pandas==2.2.1
  - protobuf==3.20.3
  - psutil==5.9.0
  - scikit-learn==1.3.0
  - scipy==1.12.0
  - tensorflow==2.12.0
name: mlflow-env
